### GET request with a header
GET http://localhost:8080/api/circuit-breaker/1
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/circuit-breaker/2
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/circuit-breaker/3
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/rate-limiter
Accept: application/json
