spring:
  application:
    name: spring-resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        #        automatic-transition-from-open-to-half-open-enabled: true # wait-duration-in-open-state 설정 시간 지난 후 Circuit 의 상태가 OPEN -> HALF_OPEN 으로 변경
        wait-duration-in-open-state: 5s
        slow-call-duration-threshold: 3s
    instances:
      jh:
        base-config: default
        minimum-number-of-calls: 3
  ratelimiter:
    configs:
      default:
        # 10초동안 최대 5회의 호출이 가능한 RateLimiter
        timeout-duration: 1s # 접근 허가를 위해 대기하는 시간
        limit-refresh-period: 10s # cycle 이 초기화 되는 주기
        limit-for-period: 5 # cycle 동안 호출 가능한 횟수

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always


