spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test-db?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234